2nd round of over-time-additions
lazersos/matlabVMEC pull request #4
Opened 2022-03-29 08:27 UTC by kudav

Keeping this in one place now. I'll go over and check some of the heavier-edited functions and review which changes should be incorporated.

2022-03-29 08:32 UTC, kudav commented on VMEC/VMECplot.m
> +                isotoro(r,z,phi,handles.rval, 'STL');
This default writing of stl files probably shouldnt be added to the main branch - perhaps there could be a button similar to Plot to file?

2022-03-29 09:25 UTC, lazersos commented on VMEC/VMECplot.m
> +                isotoro(r,z,phi,handles.rval, 'STL');
@kudav This would be a nice feature.  I would suggest though you remove this from `VMECplot.m` and open an enhancement issue to this point.

2022-03-29 09:40 UTC, lazersos requested changes
There are some things which need to cleared up before we can merge.

2022-03-29 09:40 UTC, lazersos commented on ASCOT5/ascot5_plotorbits_Backup.m
> +function fig = ascot5_plotorbits(a5file,runid,varargin)
Do we really need this function?

2022-03-29 09:40 UTC, lazersos commented on ASCOT5/ascot5_plotwall.m
> +    %set(hp,'AmbientStrength',1.0,'SpecularStrength',0.75,'DiffuseStrength',1);
Aren't these lines overridden by the ones outside the if statement?

2022-03-29 09:40 UTC, lazersos commented on ASCOT5/ascot5_walloverview.m
> +fig=figure('Position',[1 1 1920 768],'Color','white','InvertHardCopy','off');
Change 1920 to 1024 because some monitors aren't that large.

2022-03-29 09:40 UTC, lazersos commented on BEAMS3D/beams3d_beamnamelist_temp.m
> +function beams3d_beamnamelist_temp(vmec_data,energy,power,r_beam,phi_beam,z_beam,div_beam,varargin)
Why do we need this one?

2022-03-29 09:40 UTC, lazersos commented on BEAMS3D/beams3d_slow.m
> +%
Why is this commented out?

2022-03-29 09:40 UTC, lazersos commented on BEAMS3D/beams3d_write_gc.m
> -lplot=0;
Are these removals a good idea?

2022-03-29 09:40 UTC, lazersos commented on BEAMS3D/read_beams3d.m
> +function data = read_beams3d(filename, varargin)
Why add varargin if you don't use it?

2022-03-29 09:40 UTC, lazersos commented on BEAMS3D/w7x_beam_params.m
> +    E_RUDI = (50:10:250) * 1000; %20-60 kV
This isn't RUDIX but OPTEMIST.  Maybe make OPTEMIST a separate option.

2022-03-29 09:40 UTC, lazersos commented on VMEC/VMECplot.m
> +                isotoro(r,z,phi,handles.rval,f, 'STL');
Remove.

2022-03-29 09:40 UTC, lazersos commented on VMEC/VMECplot.m
> +            isotoro(handles.r,handles.z,handles.zeta,handles.rval, 'STL');
Remove.

2022-03-29 12:28 UTC, kudav commented on BEAMS3D/beams3d_beamnamelist_temp.m
> +function beams3d_beamnamelist_temp(vmec_data,energy,power,r_beam,phi_beam,z_beam,div_beam,varargin)
We don't, I removed it

2022-03-29 12:28 UTC, kudav commented on BEAMS3D/beams3d_write_gc.m
> -lplot=0;
No, undone.

2022-03-29 12:29 UTC, kudav commented on BEAMS3D/read_beams3d.m
> +function data = read_beams3d(filename, varargin)
Removed.

2022-03-29 12:30 UTC, kudav commented on BEAMS3D/beams3d_slow.m
> +%
Undone

2022-03-31 06:49 UTC, lazersos commented on BEAMS3D/beams3d_finddex.m
>          [~,B] = max(beam_data.R_lines(:,:)==0,[],1); %Much faster, but test to see if it works!
This comment makes me think you haven't tested it.  Can you verify?

2022-03-31 06:53 UTC, lazersos requested changes

2022-03-31 06:53 UTC, lazersos commented on BEAMS3D/beams3d_finddex.m
>          [~,B] = max(beam_data.R_lines(:,:)==0,[],1); %Much faster, but test to see if it works!
Please verify that this works correctly (or remove comment if it does).

2022-03-31 07:14 UTC, lazersos approved these changes
OK looks all good.

2022-03-31 07:14 UTC, merged