Kulla
lazersos/matlabVMEC pull request #8
Opened 2023-09-12 08:44 UTC by kudav

Various changes, I'll start with feature branches here from now on as well:

beams3d_slow:
- reorganized function
- implemented new collision operators
- option to supply multiple ion species

beams3d_apply_bpert:
- improvements to calculation

beams3d_normdist:
- made version check meaningful

beams3d_from_fidasim:
- to be implemented

fieldlines_follow:
- check for file type (beams3d or fieldlines), and appropriate procedure

plot_fieldlines:
- added option for color coding the traced path lenght
- added keyboard movement

VMECplot:
-  now has STL export of equilibria
- option to show min/max values in 2D plots

isotoro:
- option for specifying file name

read_hdf5:
- fix for reading in subgroup attributes

plot_fidasim:
- Neutral density plots
- birth profiles
- 2D profiles
- supplying indices for toroidal and poloidal slices

get_bes_fida_aug_data.m:
- added option for plotting the background bremsstrahlung profile
- fixed instrument function

plot_fidasim_profiles:
- option for background bremsstrahlung
- specify plotting line style

New functions:
- beams3d_suv2rzp converts points (ie the beams3d distribution grid) to cylindrical coordinates
- beams3d_calc_beamdensity calculates the 3D beam density distribution - should be merged with beams3d_beamdensity

I need to clean up some things before merging, so this is a draft for now.

2024-01-23 10:45 UTC, lazersos reviewed
There are a few points to clarify.  Also we should probably create a separate FIDASIM directory for FIDASIM routines.

2024-01-23 10:45 UTC, lazersos commented on BEAMS3D/beams3d_calc_srhoxi.m
Proper header text with description, date, version, author, and example usage required.

2024-01-23 10:45 UTC, lazersos commented on BEAMS3D/beams3d_from_fidasim.m
Proper header text with description, date, version, author, and example usage required.

2024-01-23 10:45 UTC, lazersos commented on WALL/plot_wall_acc.m
This isn't the behavior we want, is it?

2024-01-23 10:45 UTC, lazersos commented on utilities/get_bes_fida_aug_data.m
AUG specific routines should be in a separate AUG repository like we do for W7-X.

2024-01-24 17:09 UTC, kudav reviewed
Addressed the points and cleaned up the superfluous/unfinished routines.

2024-01-25 10:08 UTC, lazersos requested changes
Still a couple more things to do.

2024-01-25 10:08 UTC, lazersos commented on BEAMS3D/beams3d_suv2rzp.m
Needs proper help header.

2024-01-25 10:08 UTC, lazersos commented on BEAMS3D/beams3d_slow.m
Can you show that this routine returns simliar results to the old routine for the proper selection of log_type?

2024-01-25 15:30 UTC, lazersos requested changes
Still have to give a proper header and show that slow produces similar results.

2024-01-25 15:30 UTC, lazersos commented on BEAMS3D/beams3d_suv2rzp.m
Still needs a 'proper' header like other files.

2024-01-26 15:06 UTC, kudav commented
Here is the heating plot from beams3d_slow with the current commit (first) and from commit 18707fd7a328bd6a6156583a45ba8ad5bb9638ab (second), which was where we introduced the multiple coulomb logarithms:
slow=beams3d_slow(data,'NRL','plots');
![grafik](https://github.com/lazersos/matlabVMEC/assets/72251199/a61aedf5-bd4b-49e6-a2e9-3dcc41576a97)
slow=beams3d_slow(data,'NRLions_logarithm','plots');
![grafik](https://github.com/lazersos/matlabVMEC/assets/72251199/3d794a05-96e5-4b6e-b9e9-e2f0d40ba507)
The calculation between the two did not change, thus the output is numerically the same.

2024-01-26 15:11 UTC, lazersos approved these changes
Merge. We will add your biological and technological distinctiveness to our own.

2024-01-26 15:11 UTC, lazersos commented on BEAMS3D/beams3d_slow.m
Confirmed.

2024-01-26 15:15 UTC, merged